name: hello world
on: workflow_dispatch
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
      - name: build step
        run: echo" hii hruthik"
test:
    runs-on: ubuntu-latest
    steps: 
      - name: test step
        run: echo "nin nkn"
      
    
