name: demo of inputs
on: 
 workflow_dispatch:
   inputs:
     environment:
       description: this is the demo  of inputs'
       required: true
       default: dev
 jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run: echo "hello ${{ inputs.environment }}"
