name: inputs-demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: chose the environment to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod
      artifact_tag:
        description: chose the version of the artifact to be deployed
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: demo of inputs
        run: echo "the environment is ${{ inputs.environment }} and the artifact tag is ${{ inputs.artifact_tag }}"
