name: demo of env
on: workflow_dispatch
env:
 app_env: "dev"
jobs:
  env_demo:
   env:
    app_env: "test"
   runs-on: ubuubuntu-latest
   steps:
     - name: connecting to variables
       run: echo "hii this from $app_env department"
    
  
